import { FastifyBaseLogger, FastifyInstance, FastifyReply, FastifyRequest, FastifySchema, FastifyTypeProviderDefault, RawServerDefault } from "fastify";
import { ResolveFastifyRequestType } from "fastify/types/type-provider";
import { IncomingMessage, ServerResponse } from "node:http";
import type { RouteHandlers } from "../generated/openapi/fastify.gen";
import { CancelPurchaseData, CancelPurchaseErrors, CancelPurchaseResponses, CreateGroupData, CreateGroupErrors, CreateGroupResponses, CreateItemData, CreateItemErrors, CreateItemResponses, DeleteGroupData, DeleteGroupErrors, DeleteGroupResponses, DeleteItemData, DeleteItemErrors, DeleteItemResponses, GetDashboardResponses, GetExchangeRatesResponses, GetGroupData, GetGroupErrors, GetGroupResponses, GetGroupsResponses, GetItemData, GetItemErrors, GetItemResponses, GetMeResponses, PurchaseItemData, PurchaseItemErrors, PurchaseItemResponses, UpdateGroupData, UpdateGroupErrors, UpdateGroupResponses, UpdateItemData, UpdateItemErrors, UpdateItemResponses } from "../generated/openapi/types.gen";

export const handlers: RouteHandlers = {
    getMe: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Reply: GetMeResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Reply: GetMeResponses; }>>, reply: FastifyReply<{ Reply: GetMeResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, GetMeResponses>): void | GetMeResponses | Promise<void | GetMeResponses> {
        throw new Error("Function not implemented.");
    },
    getDashboard: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Reply: GetDashboardResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Reply: GetDashboardResponses; }>>, reply: FastifyReply<{ Reply: GetDashboardResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, GetDashboardResponses>): void | GetDashboardResponses | Promise<void | GetDashboardResponses> {
        throw new Error("Function not implemented.");
    },
    getGroups: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Reply: GetGroupsResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Reply: GetGroupsResponses; }>>, reply: FastifyReply<{ Reply: GetGroupsResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, GetGroupsResponses>): void | GetGroupsResponses | Promise<void | GetGroupsResponses> {
        throw new Error("Function not implemented.");
    },
    createGroup: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Body: CreateGroupData["body"]; Reply: CreateGroupErrors & CreateGroupResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Body: CreateGroupData["body"]; Reply: CreateGroupErrors & CreateGroupResponses; }>>, reply: FastifyReply<{ Body: CreateGroupData["body"]; Reply: CreateGroupErrors & CreateGroupResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, CreateGroupErrors & CreateGroupResponses>): void | (CreateGroupErrors & CreateGroupResponses) | Promise<void | (CreateGroupErrors & CreateGroupResponses)> {
        throw new Error("Function not implemented.");
    },
    deleteGroup: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Params: DeleteGroupData["path"]; Reply: DeleteGroupErrors & DeleteGroupResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Params: DeleteGroupData["path"]; Reply: DeleteGroupErrors & DeleteGroupResponses; }>>, reply: FastifyReply<{ Params: DeleteGroupData["path"]; Reply: DeleteGroupErrors & DeleteGroupResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, DeleteGroupErrors & DeleteGroupResponses>): void | (DeleteGroupErrors & DeleteGroupResponses) | Promise<void | (DeleteGroupErrors & DeleteGroupResponses)> {
        throw new Error("Function not implemented.");
    },
    getGroup: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Params: GetGroupData["path"]; Reply: GetGroupErrors & GetGroupResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Params: GetGroupData["path"]; Reply: GetGroupErrors & GetGroupResponses; }>>, reply: FastifyReply<{ Params: GetGroupData["path"]; Reply: GetGroupErrors & GetGroupResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, GetGroupErrors & GetGroupResponses>): void | (GetGroupErrors & GetGroupResponses) | Promise<void | (GetGroupErrors & GetGroupResponses)> {
        throw new Error("Function not implemented.");
    },
    updateGroup: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Body: UpdateGroupData["body"]; Params: UpdateGroupData["path"]; Reply: UpdateGroupErrors & UpdateGroupResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Body: UpdateGroupData["body"]; Params: UpdateGroupData["path"]; Reply: UpdateGroupErrors & UpdateGroupResponses; }>>, reply: FastifyReply<{ Body: UpdateGroupData["body"]; Params: UpdateGroupData["path"]; Reply: UpdateGroupErrors & UpdateGroupResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, UpdateGroupErrors & UpdateGroupResponses>): void | (UpdateGroupErrors & UpdateGroupResponses) | Promise<void | (UpdateGroupErrors & UpdateGroupResponses)> {
        throw new Error("Function not implemented.");
    },
    createItem: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Body: CreateItemData["body"]; Params: CreateItemData["path"]; Reply: CreateItemErrors & CreateItemResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Body: CreateItemData["body"]; Params: CreateItemData["path"]; Reply: CreateItemErrors & CreateItemResponses; }>>, reply: FastifyReply<{ Body: CreateItemData["body"]; Params: CreateItemData["path"]; Reply: CreateItemErrors & CreateItemResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, CreateItemErrors & CreateItemResponses>): void | (CreateItemErrors & CreateItemResponses) | Promise<void | (CreateItemErrors & CreateItemResponses)> {
        throw new Error("Function not implemented.");
    },
    deleteItem: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Params: DeleteItemData["path"]; Reply: DeleteItemErrors & DeleteItemResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Params: DeleteItemData["path"]; Reply: DeleteItemErrors & DeleteItemResponses; }>>, reply: FastifyReply<{ Params: DeleteItemData["path"]; Reply: DeleteItemErrors & DeleteItemResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, DeleteItemErrors & DeleteItemResponses>): void | (DeleteItemErrors & DeleteItemResponses) | Promise<void | (DeleteItemErrors & DeleteItemResponses)> {
        throw new Error("Function not implemented.");
    },
    getItem: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Params: GetItemData["path"]; Reply: GetItemErrors & GetItemResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Params: GetItemData["path"]; Reply: GetItemErrors & GetItemResponses; }>>, reply: FastifyReply<{ Params: GetItemData["path"]; Reply: GetItemErrors & GetItemResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, GetItemErrors & GetItemResponses>): void | (GetItemErrors & GetItemResponses) | Promise<void | (GetItemErrors & GetItemResponses)> {
        throw new Error("Function not implemented.");
    },
    updateItem: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Body: UpdateItemData["body"]; Params: UpdateItemData["path"]; Reply: UpdateItemErrors & UpdateItemResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Body: UpdateItemData["body"]; Params: UpdateItemData["path"]; Reply: UpdateItemErrors & UpdateItemResponses; }>>, reply: FastifyReply<{ Body: UpdateItemData["body"]; Params: UpdateItemData["path"]; Reply: UpdateItemErrors & UpdateItemResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, UpdateItemErrors & UpdateItemResponses>): void | (UpdateItemErrors & UpdateItemResponses) | Promise<void | (UpdateItemErrors & UpdateItemResponses)> {
        throw new Error("Function not implemented.");
    },
    cancelPurchase: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Params: CancelPurchaseData["path"]; Reply: CancelPurchaseErrors & CancelPurchaseResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Params: CancelPurchaseData["path"]; Reply: CancelPurchaseErrors & CancelPurchaseResponses; }>>, reply: FastifyReply<{ Params: CancelPurchaseData["path"]; Reply: CancelPurchaseErrors & CancelPurchaseResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, CancelPurchaseErrors & CancelPurchaseResponses>): void | (CancelPurchaseErrors & CancelPurchaseResponses) | Promise<void | (CancelPurchaseErrors & CancelPurchaseResponses)> {
        throw new Error("Function not implemented.");
    },
    purchaseItem: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Body: PurchaseItemData["body"]; Params: PurchaseItemData["path"]; Reply: PurchaseItemErrors & PurchaseItemResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Body: PurchaseItemData["body"]; Params: PurchaseItemData["path"]; Reply: PurchaseItemErrors & PurchaseItemResponses; }>>, reply: FastifyReply<{ Body: PurchaseItemData["body"]; Params: PurchaseItemData["path"]; Reply: PurchaseItemErrors & PurchaseItemResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, PurchaseItemErrors & PurchaseItemResponses>): void | (PurchaseItemErrors & PurchaseItemResponses) | Promise<void | (PurchaseItemErrors & PurchaseItemResponses)> {
        throw new Error("Function not implemented.");
    },
    getExchangeRates: function (this: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>, request: FastifyRequest<{ Reply: GetExchangeRatesResponses; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<FastifyTypeProviderDefault, FastifySchema, { Reply: GetExchangeRatesResponses; }>>, reply: FastifyReply<{ Reply: GetExchangeRatesResponses; }, RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, unknown, FastifySchema, FastifyTypeProviderDefault, GetExchangeRatesResponses>): void | GetExchangeRatesResponses | Promise<void | GetExchangeRatesResponses> {
        throw new Error("Function not implemented.");
    }
};